
COMPARTMENT_ID=ocid1.tenancy.oc1..aaaaaaaatregglab7rh2mz7dvureybieezfam23xqfcd5shuegazmc2kq5ba
VCN_ID=ocid1.vcn.oc1.eu-frankfurt-1.amaaaaaaf7tpnxyad5s3nbt25qi7qcqtruqbzgowxbukmlakgzmw3xwz2euq

DISPLAY_NAME="SSH Configuration"
